/**
 * GENERATED by scripts/align.py. Do not hand-edit.
 * Timings are measured against the real voiceover, not estimated.
 */
export const TIMINGS_ARE_MEASURED = true;
export const AUDIO_DURATION = 53.447;
export const TIMINGS: { start: number; end: number }[] =
[
  {
    "start": 0.0,
    "end": 10.602
  },
  {
    "start": 10.602,
    "end": 15.932
  },
  {
    "start": 15.932,
    "end": 27.123
  },
  {
    "start": 27.123,
    "end": 34.471
  },
  {
    "start": 34.471,
    "end": 41.347
  },
  {
    "start": 41.347,
    "end": 47.629
  },
  {
    "start": 47.629,
    "end": 53.447
  }
];
