/**
 * GENERATED by scripts/align.py. Do not hand-edit.
 * Timings are measured against the real voiceover, not estimated.
 */
export const TIMINGS_ARE_MEASURED = true;
export const AUDIO_DURATION = 48.300;
export const TIMINGS: { start: number; end: number }[] =
[
  {
    "start": 0.0,
    "end": 8.487
  },
  {
    "start": 8.487,
    "end": 13.775
  },
  {
    "start": 13.775,
    "end": 23.414
  },
  {
    "start": 23.414,
    "end": 31.414
  },
  {
    "start": 31.414,
    "end": 37.963
  },
  {
    "start": 37.963,
    "end": 43.221
  },
  {
    "start": 43.221,
    "end": 48.3
  }
];
